services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: monitana_backend
    environment:
      MONGO_URL: $MONGO_URL
      DB_NAME: $DB_NAME
      PORT_HTTP: $PORT_HTTP
      PORT_TCP: $PORT_TCP
      REDIS_URL: $REDIS_URL
    ports:
      - "5006:5006"

  logstash:
    image: elastic/logstash:9.1.2
    container_name: monitana_logstash
    ports:
      - "5044:5044"
    volumes:
      - /home/akiro/docker/logstash/pipeline:/usr/share/logstash/pipeline

  mongodb:
    image: mongo:latest
    container_name: monitana_mongodb
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:latest
    container_name: monitana_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - monitana_redis:/data

volumes:
  monitana_redis: