services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: monitana_backend
    environment:
      MONGO_URL: $MONGO_URL
      DB_NAME: $DB_NAME
      PORT_HTTP: $PORT_HTTP
      PORT_TCP: $PORT_TCP
      REDIS_URL: $REDIS_URL
    depends_on:
        - mongodb
        - redis
        - logstash
    ports:
      #tcp
      - "5006:5002" 
      #http
      - "5007:5000"
    networks:
      - monitana_network

  logstash:
    image: elastic/logstash:9.1.2
    container_name: monitana_logstash
    ports:
      - "5044:5044"
    volumes:
      - /home/akiro/docker/logstash/pipeline:/usr/share/logstash/pipeline

  mongodb:
    image: mongo:latest
    container_name: monitana_mongodb
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks:
      - monitana_network

  redis:
    image: redis:latest
    container_name: monitana_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - monitana_redis:/data
    networks:
      - monitana_network

volumes:
  monitana_redis:

networks:
  monitana_network:
    driver: bridge
